-- Animal adoption status (for animals)
CREATE TYPE ANIMAL_STATUS AS ENUM (
    'Adoptable',
    'Foster',
    'Adopted',
    'Hold',
    'Pending');

CREATE TABLE ANIMAL (
    A_ANIMALID    SERIAL PRIMARY KEY,
    A_NAME        VARCHAR(100) NOT NULL,
    A_SPECIES     VARCHAR(30)  NOT NULL,
    A_BREED       VARCHAR(30),
    A_STATUS      ANIMAL_STATUS NOT NULL,
    A_INTAKEDATE  DATE NOT NULL
);

-- User roles
CREATE TYPE USER_ROLE AS ENUM ('Staff', 'Adopter');

CREATE TABLE APP_USER (
    U_USERID    SERIAL PRIMARY KEY,
    U_NAME      VARCHAR(100) NOT NULL,
    U_EMAIL     VARCHAR(255) NOT NULL UNIQUE,
    U_PASSWORD  VARCHAR(100) NOT NULL,
    U_ROLE      USER_ROLE NOT NULL
);

-- Adoption request status (for requests)
CREATE TYPE REQUEST_STATUS AS ENUM (
    'Submitted',
    'Under Review',
    'Approved',
    'Rejected',
    'Cancelled'
);

CREATE TABLE ADOPTION_REQUEST (
    AR_USERID     INTEGER NOT NULL REFERENCES APP_USER(U_USERID),
    AR_ANIMALID   INTEGER NOT NULL REFERENCES ANIMAL(A_ANIMALID),
    AR_STATUS     REQUEST_STATUS NOT NULL DEFAULT 'Submitted',
    AR_CREATEDAT  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    AR_UPDATEDAT  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE MEDICAL_RECORD (
    MR_RECORDID      SERIAL PRIMARY KEY,
    MR_ANIMALID      INTEGER NOT NULL REFERENCES ANIMAL(A_ANIMALID),
    MR_TREATMENTTYPE VARCHAR NOT NULL,
    MR_TREATMENTDATE DATE NOT NULL
);

-- Intake types and conditions
CREATE TYPE INTAKE_TYPE AS ENUM ('Stray', 'Surrendered', 'Transfer');
CREATE TYPE INTAKE_CONDITION AS ENUM ('Normal', 'Injured', 'Sick');

CREATE TABLE INTAKE_RECORD (
    IR_INTAKEID     SERIAL PRIMARY KEY,
    IR_ANIMALID     INTEGER NOT NULL REFERENCES ANIMAL(A_ANIMALID),
    IR_INTAKETYPE   INTAKE_TYPE NOT NULL,
    IR_INTAKEDATE   DATE NOT NULL,
    IR_CONDITION    INTAKE_CONDITION NOT NULL
);



